#!/usr/bin/python

MODE_SCAN = 0
MODE_SEARCH = 1
MODE__VALUES = (MODE_SCAN, MODE_SEARCH)

KEY_CODE_MENU = "M"
KEY_CODE_F = "F"
KEY_CODE_H = "H"
KEY_CODE_SCAN = KEY_CODE_SEARCH = "S"
KEY_CODE_L = KEY_CODE_O = "L"
KEY_CODE_LIGHT = KEY_CODE_LOCK = "!"
KEY_CODE_1 = KEY_CODE_PRI = "1"
KEY_CODE_2 = KEY_CODE_WX = "2"
KEY_CODE_3 = "3"
KEY_CODE_4 = "4"
KEY_CODE_5 = "5"
KEY_CODE_6 = "6"
KEY_CODE_7 = KEY_CODE_RCL = "3"
KEY_CODE_8 = "8"
KEY_CODE_9 = "9"
KEY_CODE_0 = "0"
KEY_CODE_DOT = KEY_CODE_NO = KEY_CODE_REV = "."
KEY_CODE_E = KEY_CODE_YES = KEY_CODE_ATT = "E"
KEY_CODE_VFO_RIGHT = ">" # * Set "P" to KEY_MODE.
KEY_CODE_VFO_LEFT = "<" # * Set "P" to KEY_MODE.
KEY_CODE_VFO_PUSH = "^"
KEY_CODE_POWER = "P"
KEY_CODE__VALUES = (KEY_CODE_MENU, KEY_CODE_F, KEY_CODE_H, KEY_CODE_SCAN, KEY_CODE_L, 
    KEY_CODE_LIGHT, KEY_CODE_1, KEY_CODE_2, KEY_CODE_3, KEY_CODE_4, KEY_CODE_5, 
    KEY_CODE_6, KEY_CODE_7, KEY_CODE_8, KEY_CODE_9, KEY_CODE_0, KEY_CODE_DOT, 
    KEY_CODE_E, KEY_CODE_VFO_RIGHT, KEY_CODE_VFO_LEFT, KEY_CODE_VFO_PUSH, KEY_CODE_POWER)

KEY_MODE_PRESS = "P" # One Push
KEY_MODE_LONG = "L" # Press and Hold for a few second
KEY_MODE_HOLD = "H" # Press and Hold until Release receive
KEY_MODE_RELEASE = "R" # Cancel Hold state
KEY_MODE__VALUES = (KEY_MODE_PRESS, KEY_MODE_LONG, KEY_MODE_HOLD, KEY_MODE_RELEASE)

MOD_AUTO = "AUTO"
MOD_FM = "FM"
MOD_NFM = "NFM"
MOD_AM = "AM"
MOD__VALUES = (MOD_AUTO, MOD_FM, MOD_NFM, MOD_AM)

ICON_OFF = "0"
ICON_ON = "1"
ICON_BLINK = "2"
ICON__VALUES = (ICON_OFF, ICON_ON, ICON_BLINK)

BACKLIGHT_INFINITE = "IF"
BACKLIGHT_10SEC = "10"
BACKLIGHT_30SEC = "30"
BACKLIGHT_KEYPRESS = "KY"
BACKLIGHT_SQUELCH = "SQ"
BACKLIGHT__VALUES = (BACKLIGHT_INFINITE, BACKLIGHT_10SEC, BACKLIGHT_30SEC,
    BACKLIGHT_KEYPRESS, BACKLIGHT_SQUELCH)

BATT_SAVE_ON = "1"
BATT_SAVE_OFF = "0"
BATT_SAVE__VALUES = (BATT_SAVE_ON, BATT_SAVE_OFF)

PRIORITY_OFF = "0"
PRIORITY_ON = "1"
PRIORITY_PLUS = "2"
PRIORITY__VALUES = (PRIORITY_OFF, PRIORITY_ON, PRIORITY_PLUS)

QUICK_LOCKOUT_KEY_0 = 1
QUICK_LOCKOUT_KEY_1 = 2
QUICK_LOCKOUT_KEY_2 = 4
QUICK_LOCKOUT_KEY_3 = 8
QUICK_LOCKOUT_KEY_4 = 16
QUICK_LOCKOUT_KEY_5 = 32
QUICK_LOCKOUT_KEY_6 = 64
QUICK_LOCKOUT_KEY_7 = 128
QUICK_LOCKOUT_KEY_8 = 256
QUICK_LOCKOUT_KEY_9 = 512
QUICK_LOCKOUT_KEY__VALUES = (QUICK_LOCKOUT_KEY_0, QUICK_LOCKOUT_KEY_1,
    QUICK_LOCKOUT_KEY_2, QUICK_LOCKOUT_KEY_3, QUICK_LOCKOUT_KEY_4, QUICK_LOCKOUT_KEY_5,
    QUICK_LOCKOUT_KEY_6, QUICK_LOCKOUT_KEY_7, QUICK_LOCKOUT_KEY_8, QUICK_LOCKOUT_KEY_9)

SYSTEM_TYPE_CONVENTIONAL = "CNV"
SYSTEM_TYPE_MOT_800_T2_STD = "M82S"
SYSTEM_TYPE_MOT_800_T2_SPL = "M82P"
SYSTEM_TYPE_MOT_900_T2 = "M92"
SYSTEM_TYPE_MOT_VHF_T2 = "MV2"
SYSTEM_TYPE_MOT_UHF_T2 = "MU2"
SYSTEM_TYPE_MOT_800_T1_STD = "M81S"
SYSTEM_TYPE_MOT_800_T1_SPL = "M81P"
SYSTEM_TYPE_EDACS_NARROW = "EDN"
SYSTEM_TYPE_EDACS_WIDE = "EDW"
SYSTEM_TYPE_EDACS_SCAT = "EDS"
SYSTEM_TYPE_LTR = "LTR"
SYSTEM_TYPE_MOT_800_T2_CUS = "M82C"
SYSTEM_TYPE_MOT_800_T1_CUS = "M81C"
SYSTEM_TYPE__VALUES = (SYSTEM_TYPE_CONVENTIONAL, SYSTEM_TYPE_MOT_800_T2_STD, 
    SYSTEM_TYPE_MOT_800_T2_SPL, SYSTEM_TYPE_MOT_900_T2, SYSTEM_TYPE_MOT_VHF_T2, 
    SYSTEM_TYPE_MOT_UHF_T2, SYSTEM_TYPE_MOT_800_T1_STD, SYSTEM_TYPE_MOT_800_T1_SPL, 
    SYSTEM_TYPE_EDACS_NARROW, SYSTEM_TYPE_EDACS_WIDE, SYSTEM_TYPE_EDACS_SCAT, 
    SYSTEM_TYPE_LTR, SYSTEM_TYPE_MOT_800_T2_CUS, SYSTEM_TYPE_MOT_800_T1_CUS)

PRIORITY_MODE_OFF = "0"
PRIORITY_MODE_ON = "1"
PRIORITY_MODE_PLUS = "2"
PRIORITY_MODE__VALUES = (PRIORITY_MODE_OFF, PRIORITY_MODE_ON, PRIORITY_MODE_PLUS)

GREETING_DEFAULT = " "
GREETING_MAX_LINE_LEN = 16

CC_MODE_OFF = "0"
CC_MODE_PRI = "1"
CC_MODE_DND = "2"
CC_MODE__VALUES = (CC_MODE_OFF, CC_MODE_PRI, CC_MODE_DND)

CC_OVERRIDE_OFF = "0"
CC_OVERRIDE_ON = "1"
CC_OVERRIDE__VALUES = (CC_OVERRIDE_OFF, CC_OVERRIDE_ON)

CC_BANK_OFF = "0"
CC_BAND_ON = "1"
CC_BAND__VALUES = (CC_BANK_OFF, CC_BAND_ON)

ALERT_NONE = "N"
ALERT_BEEP = "B"
ALERT_LIGHT = "L"
ALERT_BEEP_LIGHT = "A"
ALERT__VALUES = (ALERT_NONE, ALERT_BEEP, ALERT_LIGHT, ALERT_BEEP_LIGHT)

ATTENUATION_OFF = "0"
ATTENUATION_ON = "1"
ATTENUATION__VALUES = (ATTENUATION_OFF, ATTENUATION_ON)

WEATHER_PRIORITY_OFF = "0"
WEATHER_PRIORITY_ON = "1"
WEATHER_PRIORITY__VALUES = (WEATHER_PRIORITY_OFF, WEATHER_PRIORITY_ON)

DISPLAY_LINE_MODE_NORMAL = " "
DISPLAY_LINE_MODE_REVERSE = "*"
DISPLAY_LINE_MODE_CURSOR = "_"
DISPLAY_LINE_MODE_BLINK = "#"
DISPLAY_LINE_MODE__VALUES = (DISPLAY_LINE_MODE_NORMAL, DISPLAY_LINE_MODE_REVERSE,
    DISPLAY_LINE_MODE_CURSOR, DISPLAY_LINE_MODE_BLINK)
